sudo: required #is required to use docker service in travis

language: go

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - make docker-build

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh failure $WEBHOOK_URL"

deploy:
  provider: script
  skip_cleanup: true
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make docker-push
  on:
    tags: true