apiVersion: templates.sitewhere.io/v1alpha3
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-asset-management
  labels:
      sitewhere.io/functional-area: asset-management
spec:
  configuration: 
    datastore:
      type: mongodb
      reference: tenant
