apiVersion: templates.sitewhere.io/v1alpha3
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-event-sources
  labels:
      sitewhere.io/functional-area: event-sources
spec:
  configuration:
    eventSources:
      - id: json
        type: mqtt
        decoder: json
        configuration:
          hostname: "${mqtt.host:sitewhere-infrastructure-mosquitto.default}"
          port: "${mqtt.port:1883}"
          topic: "SiteWhere/${tenant.token}/input/json"
          numThreads: 5
      - id: protobuf
        type: mqtt
        decoder: protobuf
        configuration:
          hostname: "${mqtt.host:sitewhere-infrastructure-mosquitto.default}"
          port: "${mqtt.port:1883}"
          topic: "SiteWhere/${tenant.token}/input/protobuf"
          numThreads: 1
