# permissions for end users to view instancedatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instancedatasettemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instancedatasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instancedatasets/status
  verbs:
  - get
