# permissions for end users to view instancedatasettemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instancedatasettemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instancedatasettemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instancedatasettemplates/status
  verbs:
  - get
