# permissions for end users to edit instanceconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instanceconfigurationtemplate-editor-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instanceconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instanceconfigurations/status
  verbs:
  - get
