# permissions for end users to view instanceconfigurationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instanceconfigurationtemplate-viewer-role
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - instanceconfigurationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sitewhere.io
  resources:
  - instanceconfigurationtemplates/status
  verbs:
  - get
