# permissions for end users to edit instancedatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instancedatasettemplate-editor-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instancedatasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instancedatasets/status
  verbs:
  - get
