# permissions for end users to view instanceconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instanceconfigurationtemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instanceconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instanceconfigurations/status
  verbs:
  - get
