# permissions for end users to edit tenantengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewheretenantengine-editor-role
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - tenantengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sitewhere.io
  resources:
  - tenantengines/status
  verbs:
  - get
