# permissions for end users to edit sitewherescripttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewherescripttemplate-editor-role
rules:
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - sitewherescripttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - sitewherescripttemplates/status
  verbs:
  - get
