# permissions for end users to view sitewherescriptcategories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewherescriptcategory-viewer-role
rules:
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - sitewherescriptcategories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - sitewherescriptcategories/status
  verbs:
  - get
