# permissions for end users to view sitewheretenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewheretenant-viewer-role
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - sitewheretenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sitewhere.io
  resources:
  - sitewheretenants/status
  verbs:
  - get
