# permissions for end users to edit scripts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewherescript-editor-role
rules:
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - scripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - scripts/status
  verbs:
  - get
