# permissions for end users to edit scriptcategories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewherescriptcategory-editor-role
rules:
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - scriptcategories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - scriptcategories/status
  verbs:
  - get
