# permissions for end users to view sitewhereinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewhereinstance-viewer-role
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sitewhere.io
  resources:
  - instances/status
  verbs:
  - get
