# permissions for end users to view sitewheretenantengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewheretenantengine-viewer-role
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - sitewheretenantengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sitewhere.io
  resources:
  - sitewheretenantengines/status
  verbs:
  - get
