# permissions for end users to edit sitewherescriptversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewherescriptversion-editor-role
rules:
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - sitewherescriptversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - sitewherescriptversions/status
  verbs:
  - get
