# permissions for end users to view tenantconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantconfigurationtemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantconfigurations/status
  verbs:
  - get
