# permissions for end users to edit tenantconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantconfigurationtemplate-editor-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantconfigurations/status
  verbs:
  - get
