# permissions for end users to edit tenantengineconfigurationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantengineconfigurationtemplate-editor-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantengineconfigurationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantengineconfigurationtemplates/status
  verbs:
  - get
