# permissions for end users to view tenantconfigurationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantconfigurationtemplate-viewer-role
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - tenantconfigurationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sitewhere.io
  resources:
  - tenantconfigurationtemplates/status
  verbs:
  - get
