# permissions for end users to view tenantengineconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantengineconfigurationtemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantengineconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantengineconfigurations/status
  verbs:
  - get
