# permissions for end users to edit tenantenginedatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantenginedatasettemplate-editor-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantenginedatasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantenginedatasets/status
  verbs:
  - get
