# permissions for end users to edit tenantenginedatasettemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantenginedatasettemplate-editor-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantenginedatasettemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantenginedatasettemplates/status
  verbs:
  - get
