# permissions for end users to view tenantenginedatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantenginedatasettemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantenginedatasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantenginedatasets/status
  verbs:
  - get
