# permissions for end users to view tenantdatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantdatasettemplate-viewer-role
rules:
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantdatasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.sitewhere.io
  resources:
  - tenantdatasets/status
  verbs:
  - get
