apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sitewhereinstances.sitewhere.io
  labels:
    app: sitewhere
    chart: sitewhere
    heritage: Tiller
    release: sitewhere
spec:
  group: sitewhere.io
  names:
    kind: SiteWhereInstance
    listKind: SiteWhereInstanceList
    plural: sitewhereinstances
    singular: sitewhereinstance
    shortNames:
    - swi
    categories:
    - sitewhere-io
    - core-sitewhere-io
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
