apiVersion: scripting.sitewhere.io/v1alpha3
kind: SiteWhereScriptTemplate
metadata:
  name: outbound-connectors-filter
  labels:
    sitewhere.io/functional-area: outbound-connectors
    scripting.sitewhere.io/function: filter
spec:
  name: Filter
  description: Implements an outbound connector event filter.
  interpreterType: js
  script: |
    // Available variable bindings:
    // ----------------------------
    // context: (IDeviceEventContext) Context information associated with device event.
    // event: (IDeviceEvent) Current device event being processed by connector.
    // logger: (Logger) Supports output to system logs.
    // ----------------------------
    // return value (boolean): Return true to filter event.
    // ----------------------------
    
    logger.info 'Processing Groovy event filter ...'
    return true
