# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/sitewhere.io_instances.yaml
- bases/sitewhere.io_microservices.yaml
- bases/sitewhere.io_tenants.yaml
- bases/sitewhere.io_tenantengines.yaml
- bases/scripting.sitewhere.io_scripts.yaml
- bases/scripting.sitewhere.io_scriptcategories.yaml
- bases/scripting.sitewhere.io_scripttemplates.yaml
- bases/scripting.sitewhere.io_scriptversions.yaml
- bases/templates.sitewhere.io_instanceconfigurations.yaml
- bases/templates.sitewhere.io_instancedatasets.yaml
- bases/templates.sitewhere.io_tenantconfigurations.yaml
- bases/templates.sitewhere.io_tenantdatasets.yaml
- bases/templates.sitewhere.io_tenantengineconfigurations.yaml
- bases/templates.sitewhere.io_tenantenginedatasets.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_instances.yaml
#- patches/webhook_in_microservices.yaml
#- patches/webhook_in_tenants.yaml
#- patches/webhook_in_tenantengines.yaml
#- patches/webhook_in_scripts.yaml
#- patches/webhook_in_scriptcategories.yaml
#- patches/webhook_in_scripttemplates.yaml
#- patches/webhook_in_scriptversions.yaml
#- patches/webhook_in_instanceconfigurations.yaml
#- patches/webhook_in_instancedatasets.yaml
#- patches/webhook_in_tenantconfigurations.yaml
#- patches/webhook_in_tenantdatasets.yaml
#- patches/webhook_in_tenantengineconfigurations.yaml
#- patches/webhook_in_tenantenginedatasets.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_instances.yaml
#- patches/cainjection_in_microservices.yaml
#- patches/cainjection_in_tenants.yaml
#- patches/cainjection_in_tenantengines.yaml
#- patches/cainjection_in_scripts.yaml
#- patches/cainjection_in_scriptcategories.yaml
#- patches/cainjection_in_scripttemplates.yaml
#- patches/cainjection_in_scriptversions.yaml
#- patches/cainjection_in_instanceconfigurations.yaml
#- patches/cainjection_in_instancedatasets.yaml
#- patches/cainjection_in_tenantconfigurations.yaml
#- patches/cainjection_in_tenantdatasets.yaml
#- patches/cainjection_in_tenantengineconfigurations.yaml
#- patches/cainjection_in_tenantenginedatasets.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
